[package]
name = "ellie_engine"
version_code = "BeautifulTropicalFish"
version = "3.5.0"
authors = ["Ahmetcan Aksu <ahmetcanaksu@behemehal.net>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
ellie_core = {path = "core", version = "1.0.0"}
ellie_parser = {path = "parser", version = "1.6.0", default-features = false }
ellie_runtime = {path = "runtime", version = "0.1.0" }
ellie_raw = {path = "raw", version = "0.1.0", optional = true }
path-absolutize = {version = "3.0.10", optional = true }
websocket = {version = "0.26.2", optional = true, default-features = false, features = ["sync"] }

[features]
default = ["build-cli"]
build-cli = ["path-absolutize", "websocket"]
raw = ["ellie_raw"]

[[bin]]
name = "ellie"
test = false
bench = false
required-features = ["build-cli"]  

[[bin]]
name = "value_test"
test = false
bench = false

[[bin]]
name = "type_test"
test = false
bench = false

[[bench]]
name = "benches"
harness = false

[build-dependencies]
ellie_parser = {path = "parser", version = "1.6.0", default-features = false}
ellie_core = {path = "core", version = "1.0.0"}
regex = "1.1.7"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
toml = "0.5.8"

[dev-dependencies]
criterion = { version = "0.3", features= ["html_reports"]}

[profile.release]
opt-level = 3