[package]
name = "ellie_engine"
version_code = "BeautifulTropicalFish"
version = "0.5.4"
authors = ["Ahmetcan Aksu <ahmetcanaksu@behemehal.net>", "Behemehal <info@behemehal.net>"]
edition = "2021"
license-file = "LICENSE"
default-run = "elliec"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
path-absolutize = { version = "3.0.10", optional = true }
regex = { version = "1.1.7", optional = true }
bincode = { version = "1.0", optional = true }
clap = { version = "3.1.1", optional = true }
clap_complete = { version = "3.0.0", optional = true }
ellie_core = { path = "core", version = "0.2.0" }
ellie_tokenizer = { path = "tokenizer", version = "0.2.1", default-features = false }
ellie_parser = { path = "parser", version = "0.3.0", default-features = false }
ellie_assist = { path = "EllieAssist", version = "0.1.0", optional = true }
ellie_runtime = {path = "runtime", version = "0.1.0" }
ellie_bytecode = { path = "bytecode", version = "0.1.0" }

[features]
default = ["standard_rules", "build-cli"]
build-cli = ["path-absolutize", "regex", "bincode", "clap", "clap_complete"]
ellie_asist = ["ellie_assist"]
standard_rules =  ["ellie_parser/standard_rules"]

[[bin]]
name = "elliec"
test = false
bench = false
required-features = ["build-cli"]  
features = [ "build-cli" ]

[build-dependencies]
clap = { version = "3.1.1", optional = true }
clap_complete = { version = "3.0.0", optional = true }
lazy_static = "1.4.0"
ellie_core = { path = "core", version = "0.2.0" }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
ellie_parser = {path = "parser", version = "0.3.0", default-features = false}
path-absolutize = { version = "3.0.10" }
toml = "0.5.8"
regex = { version = "1.1.7" }
ellie_tokenizer = {path = "tokenizer", version = "0.2.0", default-features = false}
bincode = { version = "1.0", optional = true }

[profile.release]
opt-level = 3
