[package]
name = "ellie_engine"
version_code = "BeautifulTropicalFish"
version = "3.7.3"
authors = ["Ahmetcan Aksu <ahmetcanaksu@behemehal.net>"]
edition = "2018"
license-file = "LICENSE"
default-run = "ellie"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
ellie_core = {path = "core", version = "1.0.0"}
ellie_tokenizer = {path = "tokenizer", version = "0.1.0"}
#ellie_parser = {path = "parser", version = "1.7.3", default-features = false }
#ellie_runtime = {path = "runtime", version = "0.1.0" }
path-absolutize = {version = "3.0.10", optional = true }
websocket = {version = "0.26.2", optional = true, default-features = false, features = ["sync"] }
regex = { version = "1.1.7", optional = true }

[features]
default = ["build-cli"]
build-cli = ["path-absolutize", "websocket", "regex"]

[[bin]]
name = "ellie"
test = false
bench = false
required-features = ["build-cli"]  

[build-dependencies]
lazy_static = "1.4.0"
#ellie_parser = {path = "parser", version = "1.7.3", default-features = false}
ellie_core = {path = "core", version = "1.0.0"}
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
toml = "0.5.8"
regex = { version = "1.1.7" }

#[dev-dependencies]
#criterion = { version = "0.3", features= ["html_reports"]}

[profile.release]
opt-level = 3