[package]
name = "ellie_engine"
version = "1.4.2"
authors = ["Behemehal <info@behemehal.net>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[lib]
name = "ellie"
path = "src/lib.rs"

[[bin]]
name = "ellie"
test = false
bench = false

[[bin]]
name = "test"
test = false
bench = false