language = "C"
header = """/*
    Copyright (c) 2020 Behemehal. See license file for details
*/"""
include_guard = "_ELLIE_H"
cpp_compat = true
documentation_style = "c"

[enum]
rename_variants = "QualifiedScreamingSnakeCase"

[export]
include = ["DefiniteParsed"]