[package]
name = "ellie_raw"
version = "0.1.0"
authors = ["Ahmetcan Aksu <ahmetcanco@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
ellie_parser = {path = "../parser", version = "1.7.3"}